spring:
  datasource:
    url: jdbc:mysql://localhost:3306/clinica
    username: root
    password: a1b9c2d8.
  flyway:
    baselineOnMigrate: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    web:
      pageable:
        page-parameter: pagina
        size-parameter: tamanho
        sort-parameter: ordem

#Configuração para ocultar stack trace da resposta quando este retorna uma exceção
server:
  error:
    include-stacktrace: never